import { TeamType } from '../types';

const mockManCityTeam: TeamType = {
  id: 65,
  area: {
    id: 2072,
    name: 'England',
  },
  activeCompetitions: [
    {
      id: 2021,
      area: {
        id: 2072,
        name: 'England',
      },
      name: 'Premier League',
      code: 'PL',
      plan: 'TIER_ONE',
      lastUpdated: '2021-04-17T02:20:14Z',
    },
  ],
  name: 'Manchester City FC',
  shortName: 'Man City',
  tla: 'MCI',
  crestUrl: 'https://crests.football-data.org/65.svg',
  address: 'SportCity Manchester M11 3FF',
  phone: '+44 (0870) 0621894',
  website: 'https://www.mancity.com',
  email: 'mancity@mancity.com',
  founded: 1880,
  clubColors: 'Sky Blue / White',
  venue: 'Etihad Stadium',
  squad: [
    {
      id: 2000,
      name: 'João Cancelo',
      position: 'Defender',
      dateOfBirth: '1994-05-27T00:00:00Z',
      countryOfBirth: 'Portugal',
      nationality: 'Portugal',
      shirtNumber: 27,
      role: 'PLAYER',
    },
    {
      id: 3182,
      name: 'Ilkay Gündogan',
      position: 'Midfielder',
      dateOfBirth: '1990-10-24T00:00:00Z',
      countryOfBirth: 'Germany',
      nationality: 'Germany',
      shirtNumber: 8,
      role: 'PLAYER',
    },
    {
      id: 3199,
      name: 'Rodri',
      position: 'Midfielder',
      dateOfBirth: '1996-06-22T00:00:00Z',
      countryOfBirth: 'Spain',
      nationality: 'Spain',
      shirtNumber: 16,
      role: 'PLAYER',
    },
    {
      id: 3222,
      name: 'Ederson',
      position: 'Goalkeeper',
      dateOfBirth: '1993-08-17T00:00:00Z',
      countryOfBirth: 'Brazil',
      nationality: 'Brazil',
      shirtNumber: 31,
      role: 'PLAYER',
    },
    {
      id: 3227,
      name: 'Fernandinho',
      position: 'Midfielder',
      dateOfBirth: '1985-05-04T00:00:00Z',
      countryOfBirth: 'Brazil',
      nationality: 'Brazil',
      shirtNumber: 25,
      role: 'PLAYER',
    },
    {
      id: 3236,
      name: 'Gabriel Jesus',
      position: 'Attacker',
      dateOfBirth: '1997-04-03T00:00:00Z',
      countryOfBirth: 'Brazil',
      nationality: 'Brazil',
      shirtNumber: 9,
      role: 'PLAYER',
    },
    {
      id: 3254,
      name: 'Bernardo Silva',
      position: 'Midfielder',
      dateOfBirth: '1994-08-10T00:00:00Z',
      countryOfBirth: 'Portugal',
      nationality: 'Portugal',
      shirtNumber: 20,
      role: 'PLAYER',
    },
    {
      id: 3311,
      name: 'Kyle Walker',
      position: 'Defender',
      dateOfBirth: '1990-05-28T00:00:00Z',
      countryOfBirth: 'England',
      nationality: 'England',
      shirtNumber: 2,
      role: 'PLAYER',
    },
    {
      id: 3313,
      name: 'John Stones',
      position: 'Defender',
      dateOfBirth: '1994-05-28T00:00:00Z',
      countryOfBirth: 'England',
      nationality: 'England',
      shirtNumber: 5,
      role: 'PLAYER',
    },
    {
      id: 3329,
      name: 'Raheem Sterling',
      position: 'Attacker',
      dateOfBirth: '1994-12-08T00:00:00Z',
      countryOfBirth: 'Jamaica',
      nationality: 'England',
      shirtNumber: 7,
      role: 'PLAYER',
    },
    {
      id: 3654,
      name: 'Kevin De Bruyne',
      position: 'Midfielder',
      dateOfBirth: '1991-06-28T00:00:00Z',
      countryOfBirth: 'Belgium',
      nationality: 'Belgium',
      shirtNumber: 17,
      role: 'PLAYER',
    },
    {
      id: 4172,
      name: 'Scott Carson',
      position: 'Goalkeeper',
      dateOfBirth: '1985-09-03T00:00:00Z',
      countryOfBirth: 'England',
      nationality: 'England',
      shirtNumber: 33,
      role: 'PLAYER',
    },
    {
      id: 4620,
      name: 'Daniel Arzani',
      position: 'Attacker',
      dateOfBirth: '1999-01-04T00:00:00Z',
      countryOfBirth: 'Iran',
      nationality: 'Australia',
      shirtNumber: null,
      role: 'PLAYER',
    },
    {
      id: 7726,
      name: 'Philippe Sandler',
      position: 'Defender',
      dateOfBirth: '1997-02-10T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 34,
      role: 'PLAYER',
    },
    {
      id: 7882,
      name: 'Benjamin Mendy',
      position: 'Defender',
      dateOfBirth: '1994-07-17T00:00:00Z',
      countryOfBirth: 'France',
      nationality: 'France',
      shirtNumber: 22,
      role: 'PLAYER',
    },
    {
      id: 7884,
      name: 'Aymeric Laporte',
      position: 'Defender',
      dateOfBirth: '1994-05-27T00:00:00Z',
      countryOfBirth: 'France',
      nationality: 'France',
      shirtNumber: 14,
      role: 'PLAYER',
    },
    {
      id: 7888,
      name: 'Phil Foden',
      position: 'Midfielder',
      dateOfBirth: '2000-05-28T00:00:00Z',
      countryOfBirth: 'England',
      nationality: 'England',
      shirtNumber: 47,
      role: 'PLAYER',
    },
    {
      id: 7889,
      name: 'Oleksandr Zinchenko',
      position: 'Defender',
      dateOfBirth: '1996-12-15T00:00:00Z',
      countryOfBirth: 'Ukraine',
      nationality: 'Ukraine',
      shirtNumber: 11,
      role: 'PLAYER',
    },
    {
      id: 8069,
      name: 'Riyad Mahrez',
      position: 'Attacker',
      dateOfBirth: '1991-02-21T00:00:00Z',
      countryOfBirth: 'France',
      nationality: 'Algeria',
      shirtNumber: 26,
      role: 'PLAYER',
    },
    {
      id: 8240,
      name: 'Nathan Aké',
      position: 'Defender',
      dateOfBirth: '1995-02-18T00:00:00Z',
      countryOfBirth: 'Netherlands',
      nationality: 'Netherlands',
      shirtNumber: 6,
      role: 'PLAYER',
    },
    {
      id: 10183,
      name: 'Rúben Dias',
      position: 'Defender',
      dateOfBirth: '1997-05-14T00:00:00Z',
      countryOfBirth: 'Portugal',
      nationality: 'Portugal',
      shirtNumber: 3,
      role: 'PLAYER',
    },
    {
      id: 16076,
      name: 'Patrick Roberts',
      position: 'Attacker',
      dateOfBirth: '1997-02-05T00:00:00Z',
      countryOfBirth: 'England',
      nationality: 'England',
      shirtNumber: 35,
      role: 'PLAYER',
    },
    {
      id: 33154,
      name: 'Ferrán Torres',
      position: 'Attacker',
      dateOfBirth: '2000-02-29T00:00:00Z',
      countryOfBirth: 'Spain',
      nationality: 'Spain',
      shirtNumber: 21,
      role: 'PLAYER',
    },
    {
      id: 48594,
      name: 'Ryōtarō Meshino',
      position: 'Attacker',
      dateOfBirth: '1998-06-18T00:00:00Z',
      countryOfBirth: 'Japan',
      nationality: 'Japan',
      shirtNumber: null,
      role: 'PLAYER',
    },
    {
      id: 48902,
      name: 'Ko Itakura',
      position: 'Defender',
      dateOfBirth: '1997-01-27T00:00:00Z',
      countryOfBirth: 'Japan',
      nationality: 'Japan',
      shirtNumber: null,
      role: 'PLAYER',
    },
    {
      id: 76596,
      name: 'Zack Steffen',
      position: 'Goalkeeper',
      dateOfBirth: '1995-04-02T00:00:00Z',
      countryOfBirth: 'United States',
      nationality: 'United States',
      shirtNumber: 13,
      role: 'PLAYER',
    },
    {
      id: 77734,
      name: 'Yangel Herrera',
      position: 'Midfielder',
      dateOfBirth: '1998-01-07T00:00:00Z',
      countryOfBirth: 'Venezuela',
      nationality: 'Venezuela',
      shirtNumber: null,
      role: 'PLAYER',
    },
    {
      id: 81179,
      name: 'Arijanet Muric',
      position: 'Goalkeeper',
      dateOfBirth: '1998-11-07T00:00:00Z',
      countryOfBirth: 'Switzerland',
      nationality: 'Kosovo',
      shirtNumber: 49,
      role: 'PLAYER',
    },
  ],
  lastUpdated: '2021-04-14T07:43:27Z',
};

export default mockManCityTeam;
